title: Tareq Anwar
description: Web Programmer
url: "https://tareqanwar.com"
author: "Tareq Anwar"
keywords: "tareq anwar, software developer, canada"
github: tareqanwar
medium: tareqanwar
twitter: trqnwr
email: trqnwr@gmail.com

exclude: ["README.md", "CNAME", "LICENSE", ".gitignore"]
include: []

permalink: pretty
timezone: Canada/Central

plugins: []

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed
  
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "base"
about:
- name: Github
  username: tareqanwar
  url: https://github.com/tareqanwar
  class: github
- name: Twitter
  username: trqnwr
  url: https://twitter.com/trqnwr
  class: twitter
- name: Email
  username: trqnwr@gmail.com
  class: email
  url: mailto:trqnwr@gmail.com
